name: PR_template

on:
  pull_request:
    branches: [main,develop]
    type: [closed]
jobs:
  build1:
    name: Build(1)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - name: hi
        run: |
         echo "${{secrets.ENV}}"
         echo "????"
         echo "merge"
         python -m test
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10.6"
      - name : pip installaction
        run: pip install -r requirements.txt

  build2:
    needs: build1
    name: Build(2)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - name: hi
        run: |
         echo "${{secrets.ENV}}"
         echo "pr.merge"
         echo "merge2"
         python -m test
        